# Generated by Django 3.2.8 on 2024-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('numero_pags', models.CharField(max_length=200)),
                ('numero_topografia', models.CharField(max_length=200)),
                ('numero_ejemplar', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
