# Generated by Django 3.2.8 on 2024-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
